### ISSUE TITLE
[Feat] : 비회원 주차

### ISSUE THREAD

**Issue by Dianuma** [prgrms-be-devcourse/NBE2-3-2-team4#27]
# 📝 개요
- 비회원 주차 API 작성

# ✔️ To-Do
- [x] 주차장 잔여 자리가 존재하는지 확인
- [x] 주차장에 차량번호가 이미 존재하는지 확인
- [x] 주차장 잔여 자리 업데이트
- [x] 주차 현황 상세에 차량 추가

## 👀 ETC
- 참고자료 등 기타 내용 작성
