### ISSUE TITLE
[Feat] 출차

### ISSUE THREAD

**Issue by Dianuma** [prgrms-be-devcourse/NBE2-3-2-team4#42]
# 📝 개요
- 주차된 차량 출차

# ✔️ To-Do
- [x] 주차 현황 상세로부터 현재 STATUS 가 주차중인 차량 중 차량 번호와 맞는 차량이 있는지 검토
- [x] 주차 현황 상세로부터 주차권 ID가 NULL 인지 판별하는 것으로 일반 주차와, 주차권 주차를 구분
- [x] 공통 - 주차 현황 상세의 STATUS 부분을 주차 종료로 변경, 출차 시간 기록
- [x] 공통 - 주차 현황 업데이트
- [ ] 일반 주차 - MAX(기본 주차 요금 + 추가 주차 요금, 일 최대 요금) -> 일자별로 구하기 (00시 기준 초기화) - 합계 요금 업데이트
- [ ] 주차권 주차 - 주차 시간을 초과했는지 판단
- [ ] 주차권 주차 주차 시간 이하 - PRICE(주차권) - 합계 요금 업데이트
- [ ] 주차권 주차 주차 시간 초과 - 주차 현황 상세 LATE_FEE(기본 주차 요금 + 추가 요금) 업데이트,
MAX(PRICE(주차권) + LATE_FEE, 일 최대 요금) -> 일자별로 구하기 (00시 기준 초기화) - 합계 요금 업데이트
- [x] 주차권 주차 - TICKET_ORDERS 상태 업데이트

## 👀 ETC
- 참고자료 등 기타 내용 작성
