### ISSUE TITLE
[Feat] : 주차

### ISSUE THREAD

**Issue by Dianuma** [prgrms-be-devcourse/NBE2-3-2-team4#62]
# 📝 개요
- 주차

# ✔️ To-Do
- [ ] 주문 테이블 확인
- [ ] 주차 상세 현황에 추가
- [ ] 주문 테이블 업데이트

## 👀 ETC
- 참고자료 등 기타 내용 작성
