### ISSUE TITLE
[Feat] : 출차

### ISSUE THREAD

**Issue by Dianuma** [prgrms-be-devcourse/NBE2-3-2-team4#67]
# 📝 개요
- 출차

# ✔️ To-Do
- [x] 주문 테이블 주차 상태 확인
- [x] 주차 상세 현황 테이블 확인
- [x] 주차 추가요금 유무 확인 및 계산
- [x] 주차 상세 현황 테이블 업데이트
- [x] 주문 테이블 업데이트
- [x] 주차 현황 테이블 업데이트

## 👀 ETC
- 참고자료 등 기타 내용 작성
